### PR TITLE
Aksw 12437 preprocessor featurizer effectiveness

### PR DESCRIPTION
**Pull request by swatiA072**
Demo Notebook to demonstrate the effectiveness of preprocessors (and featurizers) on HeLacells dataset

### CODE REVIEW

**Comment by swatiA072** [comment]
The notebook has been updated with asked changes @raghav-akridata

**Comment by raghav-akridata** [comment]
Hey @swatiA072 PIL is being imported in the `preprocessed_image` function. Let's fix this and then we can merge. If you can, please add some comments wherever the code is a bit intricate.

```python
def preprocessed_image(self, img_arr, cmap = 'Spectral_r'):  
    """
      function that is used for preproocessing image arrays
      Parameters
      ----------
      img_arr : numpy array
        image array 
      cmap : str
        colormaps in matplotlib
      
      Returns
      -------
      all_procesed_img_arr : numpy array
        processsed image arrays 
    """
    from PIL import Image
    prep_gamma = PreProcessors(getattr(PreProcessors, str(self.preprocessor[0])))
    all_procesed_img_arr_gamma = [Image.fromarray(prep_gamma.fit_transform(img_arr[i][:,:,0], gamma=0.85)) for i in range(len(img_arr))]
    all_procesed_img_arr = np.stack(all_procesed_img_arr_gamma)

    prep_gamma = PreProcessors(getattr(PreProcessors, str(self.preprocessor[1])))
    all_procesed_img_arr_col_map = [Image.fromarray(prep_gamma.fit_transform(all_procesed_img_arr[i] , cmap = cmap)) for i in range(len(all_procesed_img_arr))]
    all_procesed_img_arr = np.stack(all_procesed_img_arr_col_map)

    return all_procesed_img_arr/255
```

**Comment by swatiA072** [comment]
@raghav-akridata Changes has been made.

**Review by sabarish-akridata — APPROVED** [review]
LGTM

**Pull request merged**
